import { CarlistingSeed } from "../../helpers/types";
import { make } from "./rawMake";
import { model } from "./rawModel";
import { image1 } from "./rawImage";
import { gearbox } from "./rawGearboxType";
import { drive } from "./rawDriveType";
import { fuel } from "./rawFuelType";

export const carlisting: CarlistingSeed[] = [
  {
    mileage: 17304,
    description: "2.0TSI R-Line 4Motion DSG",
    price: 41900,
    make: make.volkswagen,
    model: model.tiguan,
    images: [image1],
    gearboxType: gearbox.manual,
    driveType: drive.awd,
    fuelType: fuel.gasoline,
    order: null,
  },
  {
    mileage: 68939,
    description: "1.2 TSI Trendline",
    price: 11900,
    make: make.volkswagen,
    model: model.golf,
    images: [image1],
    gearboxType: gearbox.manual,
    driveType: drive.rwd,
    fuelType: fuel.gasoline,
    order: null,
  },
  {
    mileage: 74658,
    description: "1.6 TSI Trendline",
    price: 13900,
    make: make.volkswagen,
    model: model.golf,
    images: [image1],
    gearboxType: gearbox.manual,
    driveType: drive.fwd,
    fuelType: fuel.diesel,
    order: null,
  },
  {
    mileage: 9359,
    description: "1.5 TSI DSG",
    price: 32400,
    make: make.cupra,
    model: model.formentor,
    images: [image1],
    gearboxType: gearbox.automatic,
    driveType: drive.fwd,
    fuelType: fuel.gasoline,
    order: null,
  },
  {
    mileage: 18170,
    description: "2.0 TDI DSG Style",
    price: 27500,
    make: make.skoda,
    model: model.octavia,
    images: [image1],
    gearboxType: gearbox.automatic,
    driveType: drive.fwd,
    fuelType: fuel.diesel,
    order: null,
  },
  {
    mileage: 58605,
    description: "1.0 MPI Monte Carlo",
    price: 13890,
    make: make.skoda,
    model: model.fabia,
    images: [image1],
    gearboxType: gearbox.manual,
    driveType: drive.fwd,
    fuelType: fuel.gasoline,
    order: null,
  },
  {
    mileage: 22721,
    description: "2.0TSI VZ 4Drive DSG",
    price: 37600,
    make: make.cupra,
    model: model.formentor,
    images: [image1],
    gearboxType: gearbox.automatic,
    driveType: drive.awd,
    fuelType: fuel.gasoline,
    order: null,
  },
  {
    mileage: 30755,
    description: "2.0 TDI Life DSG",
    price: 23900,
    make: make.volkswagen,
    model: model.golf,
    images: [image1],
    gearboxType: gearbox.automatic,
    driveType: drive.fwd,
    fuelType: fuel.diesel,
    order: null,
  },
];
